server.modules += ( "mod_proxy" )

$HTTP["url"] =~ "^/ttyd($|/)" {
    proxy.header = (
        "upgrade" => "enable",
        "map-urlpath" => ( "/ttyd" => "/ttyd" )
    )
    proxy.server = (
        "" => (
            (
                "host" => "127.0.0.1",
                "port" => 7681
            )
        )
    )
}
